steps:
  # 1. Build Gambar Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kash-app'
      - '.'

  # 2. Push Gambar ke Registry (WAJIB sebelum Deploy)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kash-app']

  # 3. Deploy ke Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kash-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kash-app'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/kash-app'

substitutions:
  _VITE_FIREBASE_API_KEY: ''
  _VITE_FIREBASE_AUTH_DOMAIN: ''
  _VITE_FIREBASE_PROJECT_ID: ''
  _VITE_FIREBASE_STORAGE_BUCKET: ''
  _VITE_FIREBASE_MESSAGING_SENDER_ID: ''
  _VITE_FIREBASE_APP_ID: ''
  _VITE_GEMINI_API_KEY: ''
